sepal/datasets/urls.py
'''urlconf for sepal.datasets'''

from django.conf.urls.defaults import url, patterns
from sepal.datasets.views import *

urlpatterns = patterns('',
    # ex: /datasets/
    url(r'^$', DatasetList.as_view(), name='index'),

    # ex: /datasets/3/
    url(r'^(?P<pk>\d+)/$', DatasetDetail.as_view(),
        name='detail'),

    # ex: /datasets/new/
    url(r'^create/$', DatasetCreate.as_view(), name='create'),

    # ex: /datasets/3/edit/
    url(r'^(?P<pk>\d+)/edit/$', DatasetEdit.as_view(),
        name='edit'),

    # ex: /datasets/3/upload/
    url(r'^(?P<pk>\d+)/upload/$', multiple_uploader,
        name='upload'),

    # ex: /datasets/3/delete/
    url(r'^(?P<pk>\d+)/delete/$', delete_dataset,
        name='delete_dataset'),

    # ex: /datasets/3/delete_instances/
    url(r'^(?P<pk>\d+)/delete_instances/$', delete_instances,
        name='delete_instances'),
    
    # ex: /datasets/3/instances/452/delete/
    url(r'^(?P<dataset_id>\d+)/instances/(?P<pk>\d+)/delete/$',
        SingleInstanceDelete.as_view(),
        name='single_instance_delete'),

    # ex: /datasets/3/update_instances_labels/
    url(r'^(?P<dataset_id>\d+)/update_instances_labels/(?P<label_name_id>\d+)$',
        update_instances_labels,
        name='update_instances_labels'),

    # ex: /datasets/3/load_data
    url(r'^(?P<pk>\d+)/load_data/$', load_data,
        name='load_data'),
)

# URLconfs for X-editable updating
urlpatterns += patterns('',
    # ex: /datasets/3/update_name
    # X-editable dataset name
    url(r'^(?P<dataset_id>\d+)/update_name/$', update_name,
        name='update_name'),

    # ex: /datasets/3/update_description
    # X-editable dataset name
    url(r'^(?P<dataset_id>\d+)/update_description/$', update_description,
        name='update_description'),

    # ex: /datasets/3/update_description
    # X-editable dataset name
    url(r'^(?P<dataset_id>\d+)/update_species/$', update_species,
        name='update_species'),

    # ex: /datasets/instances/452/update_label/4
    # X-editable instance label
    url(r'^(?P<dataset_id>\d+)/instances/(?P<instance_id>\d+)/update_label/(?P<label_name_id>\d+)$',
        update_instance_label,
        name='update_instance_label'),

    # ex: /datasets/3/update_label/5
    # X-editable label name
    url(r'^(?P<dataset_id>\d+)/update_label/(?P<label_name_id>\d+)$',
        update_label_name,
        name='update_label_name'),
)

sepal/urls.py
""" Default urlconf for sepal """

from django.conf import settings
from django.conf.urls.defaults import include, patterns
from django.contrib import admin
admin.autodiscover()

def bad(request):
    """ Simulates a server error """
    1 / 0

urlpatterns = patterns('',
    (r'', include('sepal.base.urls')),
    (r'^celerytest/', include('sepal.celerytest.urls', namespace='celery')),
    (r'^datasets/', include('sepal.datasets.urls', namespace='datasets')),
    (r'^user/', include('sepal.user.urls', namespace='user')),
    (r'^signup/', include('sepal.signup.urls', namespace='signup')),
    (r'^admin/doc/', include('django.contrib.admindocs.urls')),
    (r'^admin/', include(admin.site.urls)),
    #url(r'^', include('debug_toolbar_user_panel.urls')),
    (r'^bad/$', bad),
)

## In DEBUG mode, serve media files through Django.
if settings.DEBUG:
    # Remove leading and trailing slashes so the regex matches.
    media_url = settings.MEDIA_URL.lstrip('/').rstrip('/')
    urlpatterns += patterns('',
        (r'^%s/(?P<path>.*)$' % media_url, 'django.views.static.serve',
         {'document_root': settings.MEDIA_ROOT}),
    )

sepal/datasets/forms.py
from django import forms
from crispy_forms.helper import FormHelper
from crispy_forms.layout import *
from sepal.datasets.models import *


class DatasetForm(forms.ModelForm):
    '''Form for creating a new dataset.
    '''
    description = forms.CharField(required=False,
        widget=forms.Textarea(attrs={'rows': 5}))
    species = forms.CharField(required=False,)

    class Meta:
        model = Dataset
        fields = ('name', 'species', 'description')

    def __init__(self, *args, **kwargs):
        self.helper = FormHelper()
        self.helper.form_id = 'datasetForm'
        self.helper.form_method = 'post'
        self.helper.add_input(Submit('submit', 'Submit'))
        super(DatasetForm, self).__init__(*args, **kwargs)


class DatasetEditForm(forms.ModelForm):
    '''Form for editing the title, species, and description
    of a dataset.
    '''
    description = forms.CharField(required=False,
        widget=forms.Textarea(attrs={'rows': 5}))

    class Meta:
        model = Dataset
        fields = ('name', 'species', 'description')

    def __init__(self, *args, **kwargs):
        self.helper = FormHelper()
        self.helper.form_id = 'datasetEditForm'
        self.helper.form_method = 'post'
        self.helper.add_input(Submit('submit', 'Submit'))
        super(DatasetEditForm, self).__init__(*args, **kwargs)

sepal/datasets/views.py
import os
from django.views.generic import View, ListView, DetailView, FormView, UpdateView, DeleteView
from django.core.urlresolvers import reverse, reverse_lazy
from django.conf import settings
from django.shortcuts import get_object_or_404
from django.utils import simplejson
from django.http import HttpResponse, HttpResponseRedirect, Http404
from django.views.decorators.csrf import ensure_csrf_cookie
from sepal.datasets.forms import DatasetForm, DatasetEditForm
from sepal.datasets.models import *
from sepal.datasets.tasks import extract_features
from django.contrib.auth.decorators import login_required

class LoggedInMixin(object):
    """ A mixin requiring a user to be logged in. """
    def dispatch(self, request, *args, **kwargs):
        if not request.user.is_authenticated():
            raise Http404
        return super(LoggedInMixin, self).dispatch(request, *args, **kwargs)

############## Dataset views ##################


class DatasetList(LoggedInMixin, ListView):
    model = Dataset
    queryset = Dataset.objects.order_by('-created_at')
    context_object_name = 'all_datasets'
    template_name = 'datasets/index.html'

    def get_queryset(self):
        if self.request.user.is_authenticated:
            return Dataset.objects.filter(user=self.request.user)
        else:
            return None


class DatasetDisplay(DetailView):
    model = Dataset
    context_object_name = 'dataset'
    template_name = 'datasets/detail.html'

    def get_context_data(self, **kwargs):
        dataset = self.get_object()
        context = dataset.get_context()
        context.update(**kwargs)
        return super(DatasetDisplay, self).get_context_data(**context)
        

def load_data(request, pk):
    
    d = Dataset.objects.get(pk=pk)
    # d.get_data()
    mimetype = 'text/plain'
    if request.is_ajax():
        mimetype = 'application/json'
    return HttpResponse(d.get_json_data(), mimetype=mimetype)

# class DatasetAddDatasource(FormView, SingleObjectMixin):
#     '''View for adding data to a dataset.
#     '''
#     model = Dataset
#     form_class = DatasourceForm
#     template_name = 'datasets/detail.html'

#     def get_context_data(self, **kwargs):
#         dataset = self.get_object()
#         print dataset
#         context = dataset.get_context()
#         context['upload_form'] = self.get_form(DatasourceForm)
#         context.update(**kwargs)
#         return super(DatasetAddDatasource, self).get_context_data(**context)

#     def get_success_url(self):
#         return reverse('datasets:detail', kwargs={'pk': self.object.pk})

#     def form_valid(self, form):
#         self.object = self.get_object()
#         if form.cleaned_data['uploaded_file']:
#             f = form.cleaned_data['uploaded_file']
#             print 'f in form_valid is type %s' % f.content_type
#             # If user uploaded an audio file
#             if f.content_type == 'audio/wav':
#                 # Create new Audio object
#                 # This uploads the file to media/audio
#                 audio_obj = Audio(audio_file=f)
#                 audio_obj.save()
#                 if audio_obj:
#                     # Create new instance and associate it with the audio file
#                     instance = Instance(dataset=self.object)
#                     instance.audio = audio_obj
#                     instance.save()
#                     extract_features(self.object.pk, instance.pk,
#                         os.path.join(settings.MEDIA_ROOT, 'audio', f.name))
#             # If user uploaded a csv file
#             elif f.content_type == 'text/csv':
#                 # Save file
#                 handle_uploaded_file(f)
#                 # Parse data and save to database
#                 read_datasource(self.object,
#                     os.path.join(settings.MEDIA_ROOT, 'data_sources', f.name))
#         return super(DatasetAddDatasource, self).form_valid(form)


def multiple_uploader(request, pk):
    '''View for handling file uploads with the jQuery multiple file upload widget.

    NOTE: must be a POST request.
    '''
    d = Dataset.objects.get(pk=pk)
    
    options = {
    # the maximum file size
    "maxfilesize": 2 * 2 ** 20,  # 2 Mb
    # the minimum file size (must be in bytes)
    "minfilesize": 1 * 2 ** 10,  # 1 Kb
    # the file types which are going to be allowed for upload
    #   must be a mimetype
    "acceptedformats": (
        "audio/wav", 'audio/x-wav', 'audio/wav', 'audio/x-wav', 'audio/wave', 'audio/vnd.wave'
        )
    }

    if request.POST:
        if request.FILES == None:
            raise Http404("No objects uploaded")

        f = request.FILES[u'files[]']
        filtered_files = Audio.objects.filter(
                                        instance__dataset=d).values_list(
                                                                'audio_file', flat=True)
        # the paths of files associated with this dataet
        filtered_paths = [os.path.join(settings.MEDIA_ROOT, file_url) for file_url in filtered_files]
        # the path where the file would be uploaded to
        file_path = os.path.join(settings.MEDIA_ROOT, 'audio', f.name)

        # initialize the error
        # If error occurs, this will have the string error message so
        # uploader can display the appropriate message
        error = False
        # check against options for errors
        # file size
        if f.size > options["maxfilesize"]:
            error = "maxFileSize"
        if f.size < options["minfilesize"]:
            error = "minFileSize"
        # allowed file type
        if f.content_type not in options["acceptedformats"]:
            error = "acceptFileTypes"
        # prevent uploading of duplicate files
        # FIXME: this validatio doesn't work after a file is deleted
        if file_path in filtered_paths:
            error = 'fileAlreadyExists'
        # FIXME: can't upload files with a space in filename
        # because spaces get converted to underscores on upload and result in a FileNotFound error
        # NOTE: this is a temporary fix
        if ' ' in f.name:
            error = 'invalidFileName'

        result = {'name': f.name,
               'size': f.size,
               }

        if error:
            # append error message
            result["error"] = error
            # generate json
            response_data = simplejson.dumps([result])
            # return response to uploader with error
            # so it can display error message
            return HttpResponse(response_data, mimetype='application/json')

        if f.content_type in ('audio/wav', 'audio/x-wav', 'audio/wave', 'audio/vnd.wave'):
            # Create new Audio object
            # This uploads the file to media/audio
            audio_obj = Audio(audio_file=f)
            audio_obj.save()
            if audio_obj:
                # Create new instance and associate it with the audio file
                instance = Instance(dataset=d)
                instance.audio = audio_obj
                instance.save()
                extract_features(d.pk, instance.pk,
                    os.path.join(settings.MEDIA_ROOT, 'audio', f.name))
                result['url'] = audio_obj.audio_file.url
                # data that is dynamically added as a table row after the upload is finished
                result['instance_data'] = instance.as_table_row()
                result['instance_id'] = instance.pk
                # Label name obj. NOTE: assumes one label per dataset
                label_name = instance.labels().keys()[0]
                result['edit_label_url'] = reverse('datasets:update_instance_label',
                                                    args=(instance.dataset.pk, instance.pk, label_name.pk))
        response_data = simplejson.dumps([result])
        mimetype = 'text/plain'
        if request.is_ajax():
            mimetype = 'application/json'
        return HttpResponse(response_data, mimetype=mimetype)
    else:
        return HttpResponse('Only POST accepted')


class DatasetDetail(View):
    '''The base dataset detail view. Handles both GET and POST requests
    '''
    def get(self, request, *args, **kwargs):
        view = ensure_csrf_cookie(DatasetDisplay.as_view())
        return view(request, *args, **kwargs)

    # def post(self, request, *args, **kwargs):
    #     view = ensure_csrf_cookie(DatasetAddDatasource.as_view())
    #     return view(request, *args, **kwargs)


class DatasetCreate(FormView):
    form_class = DatasetForm
    template_name = 'datasets/create.html'
    success_url = reverse_lazy('datasets:index')

    def form_valid(self, form):
        form.instance.user = self.request.user
        form.save()
        return super(DatasetCreate, self).form_valid(form)


class DatasetEdit(UpdateView):
    model = Dataset
    form_class = DatasetEditForm
    context_object_name = 'dataset'
    template_name = 'datasets/edit.html'
    success_url = reverse_lazy('datasets:index')


def delete_dataset(request, pk):
    '''View for deleting a dataset.
    '''
    dataset = Dataset.objects.get(pk=pk)
    dataset.delete()
    return HttpResponseRedirect(reverse('datasets:index'))

################ Instance views ####################


class SingleInstanceDelete(DeleteView):
    ''' View for deleting a single instance.
    '''
    model = Instance
    template_name = 'instances/delete.html'
    context_object_name = 'object'

    def get_success_url(self):
        return reverse_lazy('datasets:detail',
            kwargs={'pk': self.kwargs['dataset_id']})


def delete_instances(request, pk):
    '''View for deleting selected (multiple) instances.

    Must be a POST request.
    '''
    # Get the ids of the selected instances
    if request.is_ajax():
        instance_ids = [int(instance_id) for instance_id in request.POST.getlist('selected[]')]
        for id in instance_ids:
            inst_obj = Instance.objects.get(pk=id)

sepal/datasets/templates/uploader/upload_form.html
{% load url from future %}
{% load verbatim_tag %}
{% load upload_tags %}
<div id="fileupload">
    <div class="m-widget">
        <div id="upload-heading" class="m-widget-header"><h3>Extract Features</h3></div>
        <div class="m-widget-body">
            <form id="upload-form" action="{% url 'datasets:upload' dataset.pk  %}" method="POST" enctype="multipart/form-data">{% csrf_token %}
                <div class="row-fluid m-fluid fileupload-buttonbar">
                    <div class="span7">
                        <span class="btn btn-blue btn-small fileinput-button">
                            <i class="icon-plus icon-white"></i>
                            <input type="file" name="files[]" multiple>
                        </span>
                        <button name="submit-all" type="submit" class="btn btn-green btn-small start">
                            <i class="icon-upload icon-white"></i>
                            <span>Extract all</span>
                        </button>
                        <button type="reset" class="btn btn-red btn-small cancel">
                            <i class="icon-ban-circle icon-white"></i>
                            <span>Cancel</span>
                        </button>
                        <button type="button" class="btn btn-yellow btn-small delete">
                            <i class="icon-remove icon-white"></i>
                            <span>Clear</span>
                        </button>
                        <input type="checkbox" class="toggle">
                    </div><!-- end span7 -->
                    <div class="span5 fileupload-progress fade">
                        <div class="progress progress-success progres-striped active">
                            <div class="bar" style="width:0%"></div>
                        </div>
                        <div class="progress-extended">&nbsp;</div>
                    </div><!-- end span5 -->
                </div><!-- end row fileupload-button-bar -->
                <div class="fileupload-loading"></div>
            </form><!-- end form -->
            <div class="fileupload-content">
                <table class="files"></table>
                <div class="fileupload-progressbar"></div>
            </div><!-- end fileupload-content -->

            <div id="help" style="color:gray;">
                <p>.wav files only.</p>
                <p>You can select multiple files at once using Ctrl (Win) or Command (Mac), or you can drag-and-drop your files on this panel.</p>
            </div><!-- end #help -->

        </div><!-- end m-widget-body  -->
    </div><!-- end m-widget -->
</div><!-- end #fileupload -->
{% upload_js %}

<script src="{{ STATIC_URL }}multiuploader/js/jquery.ui.widget.js"></script>
<script src="{{ STATIC_URL }}multiuploader/js/tmpl.min.js"></script>
<script src="{{ STATIC_URL }}multiuploader/js/load-image.min.js"></script>
<script src="{{ STATIC_URL }}multiuploader/js/canvas-to-blob.min.js"></script>
<script src="{{ STATIC_URL }}multiuploader/js/bootstrap.min.js"></script>
<script src="{{ STATIC_URL }}multiuploader/js/bootstrap-image-gallery.min.js"></script>
<script src="{{ STATIC_URL }}multiuploader/js/jquery.iframe-transport.js"></script>
<script src="{{ STATIC_URL }}multiuploader/js/jquery.fileupload.js"></script>
<script src="{{ STATIC_URL }}multiuploader/js/jquery.fileupload-fp.js"></script>
<script src="{{ STATIC_URL }}multiuploader/js/jquery.fileupload-ui.js"></script>
<script src="{{ STATIC_URL }}multiuploader/js/locale.js"></script>
<script src="{{ STATIC_URL }}multiuploader/js/main.js"></script>
{# <script src="{{ STATIC_URL }}multiuploader/js/csrf.js"></script> #}