sepal/datasets/urls.py
'''urlconf for sepal.datasets'''

from django.conf.urls.defaults import url, patterns
from sepal.datasets.views import *

urlpatterns = patterns('',
    # ex: /datasets/
    url(r'^$', DatasetList.as_view(), name='index'),

    # ex: /datasets/3/
    url(r'^(?P<pk>\d+)/$', DatasetDetail.as_view(),
        name='detail'),

    # ex: /datasets/new/
    url(r'^create/$', DatasetCreate.as_view(), name='create'),

    # ex: /datasets/3/edit/
    url(r'^(?P<pk>\d+)/edit/$', DatasetEdit.as_view(),
        name='edit'),

    # ex: /datasets/3/upload/
    url(r'^(?P<pk>\d+)/upload/$', multiple_uploader,
        name='upload'),

    # ex: /datasets/3/delete/
    url(r'^(?P<pk>\d+)/delete/$', delete_dataset,
        name='delete_dataset'),

    # ex: /datasets/3/delete_instances/
    url(r'^(?P<pk>\d+)/delete_instances/$', delete_instances,
        name='delete_instances'),
    
    # ex: /datasets/3/instances/452/delete/
    url(r'^(?P<dataset_id>\d+)/instances/(?P<pk>\d+)/delete/$',
        SingleInstanceDelete.as_view(),
        name='single_instance_delete'),

    # ex: /datasets/3/update_instances_labels/
    url(r'^(?P<dataset_id>\d+)/update_instances_labels/(?P<label_name_id>\d+)$',
        update_instances_labels,
        name='update_instances_labels'),

    # ex: /datasets/3/load_data
    url(r'^(?P<pk>\d+)/load_data/$', load_data,
        name='load_data'),
)

# URLconfs for X-editable updating
urlpatterns += patterns('',
    # ex: /datasets/3/update_name
    # X-editable dataset name
    url(r'^(?P<dataset_id>\d+)/update_name/$', update_name,
        name='update_name'),

    # ex: /datasets/3/update_description
    # X-editable dataset name
    url(r'^(?P<dataset_id>\d+)/update_description/$', update_description,
        name='update_description'),

    # ex: /datasets/3/update_description
    # X-editable dataset name
    url(r'^(?P<dataset_id>\d+)/update_species/$', update_species,
        name='update_species'),

    # ex: /datasets/instances/452/update_label/4
    # X-editable instance label
    url(r'^(?P<dataset_id>\d+)/instances/(?P<instance_id>\d+)/update_label/(?P<label_name_id>\d+)$',
        update_instance_label,
        name='update_instance_label'),

    # ex: /datasets/3/update_label/5
    # X-editable label name
    url(r'^(?P<dataset_id>\d+)/update_label/(?P<label_name_id>\d+)$',
        update_label_name,
        name='update_label_name'),
)

sepal/urls.py
""" Default urlconf for sepal """

from django.conf import settings
from django.conf.urls.defaults import include, patterns
from django.contrib import admin
admin.autodiscover()

def bad(request):
    """ Simulates a server error """
    1 / 0

urlpatterns = patterns('',
    (r'', include('sepal.base.urls')),
    (r'^celerytest/', include('sepal.celerytest.urls', namespace='celery')),
    (r'^datasets/', include('sepal.datasets.urls', namespace='datasets')),
    (r'^user/', include('sepal.user.urls', namespace='user')),
    (r'^signup/', include('sepal.signup.urls', namespace='signup')),
    (r'^admin/doc/', include('django.contrib.admindocs.urls')),
    (r'^admin/', include(admin.site.urls)),
    #url(r'^', include('debug_toolbar_user_panel.urls')),
    (r'^bad/$', bad),
)

## In DEBUG mode, serve media files through Django.
if settings.DEBUG:
    # Remove leading and trailing slashes so the regex matches.
    media_url = settings.MEDIA_URL.lstrip('/').rstrip('/')
    urlpatterns += patterns('',
        (r'^%s/(?P<path>.*)$' % media_url, 'django.views.static.serve',
         {'document_root': settings.MEDIA_ROOT}),
    )

sepal/datasets/forms.py
from django import forms
from crispy_forms.helper import FormHelper
from crispy_forms.layout import *
from sepal.datasets.models import *


class DatasetForm(forms.ModelForm):
    '''Form for creating a new dataset.
    '''
    description = forms.CharField(required=False,
        widget=forms.Textarea(attrs={'rows': 5}))
    species = forms.CharField(required=False,)

    class Meta:
        model = Dataset
        fields = ('name', 'species', 'description')

    def __init__(self, *args, **kwargs):
        self.helper = FormHelper()
        self.helper.form_id = 'datasetForm'
        self.helper.form_method = 'post'
        self.helper.add_input(Submit('submit', 'Submit'))
        super(DatasetForm, self).__init__(*args, **kwargs)


class DatasetEditForm(forms.ModelForm):
    '''Form for editing the title, species, and description
    of a dataset.
    '''
    description = forms.CharField(required=False,
        widget=forms.Textarea(attrs={'rows': 5}))

    class Meta:
        model = Dataset
        fields = ('name', 'species', 'description')

    def __init__(self, *args, **kwargs):
        self.helper = FormHelper()
        self.helper.form_id = 'datasetEditForm'
        self.helper.form_method = 'post'
        self.helper.add_input(Submit('submit', 'Submit'))
        super(DatasetEditForm, self).__init__(*args, **kwargs)

sepal/datasets/views.py
import os
from django.views.generic import View, ListView, DetailView, FormView, UpdateView, DeleteView
from django.core.urlresolvers import reverse, reverse_lazy
from django.conf import settings
from django.shortcuts import get_object_or_404
from django.utils import simplejson
from django.http import HttpResponse, HttpResponseRedirect, Http404
from django.views.decorators.csrf import ensure_csrf_cookie
from sepal.datasets.forms import DatasetForm, DatasetEditForm
from sepal.datasets.models import *
from sepal.datasets.tasks import extract_features
from django.contrib.auth.decorators import login_required

class LoggedInMixin(object):
    """ A mixin requiring a user to be logged in. """
    def dispatch(self, request, *args, **kwargs):
        if not request.user.is_authenticated():
            raise Http404
        return super(LoggedInMixin, self).dispatch(request, *args, **kwargs)

############## Dataset views ##################


class DatasetList(LoggedInMixin, ListView):
    model = Dataset
    queryset = Dataset.objects.order_by('-created_at')
    context_object_name = 'all_datasets'
    template_name = 'datasets/index.html'

    def get_queryset(self):
        if self.request.user.is_authenticated:
            return Dataset.objects.filter(user=self.request.user)
        else:
            return None


class DatasetDisplay(DetailView):
    model = Dataset
    context_object_name = 'dataset'
    template_name = 'datasets/detail.html'

    def get_context_data(self, **kwargs):
        dataset = self.get_object()
        context = dataset.get_context()
        context.update(**kwargs)
        return super(DatasetDisplay, self).get_context_data(**context)
        

def load_data(request, pk):
    
    d = Dataset.objects.get(pk=pk)
    # d.get_data()
    mimetype = 'text/plain'
    if request.is_ajax():
        mimetype = 'application/json'
    return HttpResponse(d.get_json_data(), mimetype=mimetype)

# class DatasetAddDatasource(FormView, SingleObjectMixin):
#     '''View for adding data to a dataset.
#     '''
#     model = Dataset
#     form_class = DatasourceForm
#     template_name = 'datasets/detail.html'

#     def get_context_data(self, **kwargs):
#         dataset = self.get_object()
#         print dataset
#         context = dataset.get_context()
#         context['upload_form'] = self.get_form(DatasourceForm)
#         context.update(**kwargs)
#         return super(DatasetAddDatasource, self).get_context_data(**context)

#     def get_success_url(self):
#         return reverse('datasets:detail', kwargs={'pk': self.object.pk})

#     def form_valid(self, form):
#         self.object = self.get_object()
#         if form.cleaned_data['uploaded_file']:
#             f = form.cleaned_data['uploaded_file']
#             print 'f in form_valid is type %s' % f.content_type
#             # If user uploaded an audio file
#             if f.content_type == 'audio/wav':
#                 # Create new Audio object
#                 # This uploads the file to media/audio
#                 audio_obj = Audio(audio_file=f)
#                 audio_obj.save()
#                 if audio_obj:
#                     # Create new instance and associate it with the audio file
#                     instance = Instance(dataset=self.object)
#                     instance.audio = audio_obj
#                     instance.save()
#                     extract_features(self.object.pk, instance.pk,
#                         os.path.join(settings.MEDIA_ROOT, 'audio', f.name))
#             # If user uploaded a csv file
#             elif f.content_type == 'text/csv':
#                 # Save file
#                 handle_uploaded_file(f)
#                 # Parse data and save to database
#                 read_datasource(self.object,
#                     os.path.join(settings.MEDIA_ROOT, 'data_sources', f.name))
#         return super(DatasetAddDatasource, self).form_valid(form)


def multiple_uploader(request, pk):
    '''View for handling file uploads with the jQuery multiple file upload widget.

    NOTE: must be a POST request.
    '''
    d = Dataset.objects.get(pk=pk)
    
    options = {
    # the maximum file size
    "maxfilesize": 2 * 2 ** 20,  # 2 Mb
    # the minimum file size (must be in bytes)
    "minfilesize": 1 * 2 ** 10,  # 1 Kb
    # the file types which are going to be allowed for upload
    #   must be a mimetype
    "acceptedformats": (
        "audio/wav", 'audio/x-wav', 'audio/wav', 'audio/x-wav', 'audio/wave', 'audio/vnd.wave'
        )
    }

    if request.POST:
        if request.FILES == None:
            raise Http404("No objects uploaded")

        f = request.FILES[u'files[]']
        filtered_files = Audio.objects.filter(
                                        instance__dataset=d).values_list(
                                                                'audio_file', flat=True)
        # the paths of files associated with this dataet
        filtered_paths = [os.path.join(settings.MEDIA_ROOT, file_url) for file_url in filtered_files]
        # the path where the file would be uploaded to
        file_path = os.path.join(settings.MEDIA_ROOT, 'audio', f.name)

        # initialize the error
        # If error occurs, this will have the string error message so
        # uploader can display the appropriate message
        error = False
        # check against options for errors
        # file size
        if f.size > options["maxfilesize"]:
            error = "maxFileSize"
        if f.size < options["minfilesize"]:
            error = "minFileSize"
        # allowed file type
        if f.content_type not in options["acceptedformats"]:
            error = "acceptFileTypes"
        # prevent uploading of duplicate files
        # FIXME: this validatio doesn't work after a file is deleted
        if file_path in filtered_paths:
            error = 'fileAlreadyExists'
        # FIXME: can't upload files with a space in filename
        # because spaces get converted to underscores on upload and result in a FileNotFound error
        # NOTE: this is a temporary fix
        if ' ' in f.name:
            error = 'invalidFileName'

        result = {'name': f.name,
               'size': f.size,
               }

        if error:
            # append error message
            result["error"] = error
            # generate json
            response_data = simplejson.dumps([result])
            # return response to uploader with error
            # so it can display error message
            return HttpResponse(response_data, mimetype='application/json')

        if f.content_type in ('audio/wav', 'audio/x-wav', 'audio/wave', 'audio/vnd.wave'):
            # Create new Audio object
            # This uploads the file to media/audio
            audio_obj = Audio(audio_file=f)
            audio_obj.save()
            if audio_obj:
                # Create new instance and associate it with the audio file
                instance = Instance(dataset=d)
                instance.audio = audio_obj
                instance.save()
                extract_features(d.pk, instance.pk,
                    os.path.join(settings.MEDIA_ROOT, 'audio', f.name))
                result['url'] = audio_obj.audio_file.url
                # data that is dynamically added as a table row after the upload is finished
                result['instance_data'] = instance.as_table_row()
                result['instance_id'] = instance.pk
                # Label name obj. NOTE: assumes one label per dataset
                label_name = instance.labels().keys()[0]
                result['edit_label_url'] = reverse('datasets:update_instance_label',
                                                    args=(instance.dataset.pk, instance.pk, label_name.pk))
        response_data = simplejson.dumps([result])
        mimetype = 'text/plain'
        if request.is_ajax():
            mimetype = 'application/json'
        return HttpResponse(response_data, mimetype=mimetype)
    else:
        return HttpResponse('Only POST accepted')


class DatasetDetail(View):
    '''The base dataset detail view. Handles both GET and POST requests
    '''
    def get(self, request, *args, **kwargs):
        view = ensure_csrf_cookie(DatasetDisplay.as_view())
        return view(request, *args, **kwargs)

    # def post(self, request, *args, **kwargs):
    #     view = ensure_csrf_cookie(DatasetAddDatasource.as_view())
    #     return view(request, *args, **kwargs)


class DatasetCreate(FormView):
    form_class = DatasetForm
    template_name = 'datasets/create.html'
    success_url = reverse_lazy('datasets:index')

    def form_valid(self, form):
        form.instance.user = self.request.user
        form.save()
        return super(DatasetCreate, self).form_valid(form)


class DatasetEdit(UpdateView):
    model = Dataset
    form_class = DatasetEditForm
    context_object_name = 'dataset'
    template_name = 'datasets/edit.html'
    success_url = reverse_lazy('datasets:index')


def delete_dataset(request, pk):
    '''View for deleting a dataset.
    '''
    dataset = Dataset.objects.get(pk=pk)
    dataset.delete()
    return HttpResponseRedirect(reverse('datasets:index'))

################ Instance views ####################


class SingleInstanceDelete(DeleteView):
    ''' View for deleting a single instance.
    '''
    model = Instance
    template_name = 'instances/delete.html'
    context_object_name = 'object'

    def get_success_url(self):
        return reverse_lazy('datasets:detail',
            kwargs={'pk': self.kwargs['dataset_id']})


def delete_instances(request, pk):
    '''View for deleting selected (multiple) instances.

    Must be a POST request.
    '''
    # Get the ids of the selected instances
    if request.is_ajax():
        instance_ids = [int(instance_id) for instance_id in request.POST.getlist('selected[]')]
        for id in instance_ids:
            inst_obj = Instance.objects.get(pk=id)

sepal/datasets/templates/datasets/confirm_delete_dataset.html
{% load url from future %}
<div class="modal fade" id="delete_dataset_{{ dataset.pk }}_confirm">
  <div class="modal-header">
    <a class="close" data-dismiss="modal">×</a>
    <h3>Delete <em>{{ dataset.name }}</em>?</h3>
  </div>
  <div class="modal-body">
    <p>WARNING: This operation is irreversible.</p>
  </div>
  <div class="modal-footer">
    <a href="{% url 'datasets:delete_dataset' dataset.pk %}" class="btn btn-red">Delete</a>
    <a href="#" data-dismiss="modal" class="btn">Cancel</a>
  </div>
</div>

<script>
$('#delete_dataset_{{ dataset.pk }}').on('show', function() {
  var $submit = $(this).find('.btn-red'),
      href = $submit.attr('href');
  $submit.attr('href', href.replace('pony', $(this).data('id')));
});

$('#delete_dataset_{{ dataset.pk }}').click(function(e) {
  e.preventDefault();
  $('#delete_dataset_{{ dataset.pk }}_confirm').data('id', $(this).data('id')).modal('show');
});
</script>

sepal/datasets/templates/datasets/dataset_editable.html
{% load url from future %}
<script>
  $('#dataset-name').editable({
   type: 'text',
   pk: {{ dataset.pk }},
   url: '{% url 'datasets:update_name' dataset.pk %}',
   title: 'Edit dataset name',
   name: 'dataset-editable-name'
  });

  $('#dataset-description').editable({
   type: 'textarea',
   pk: {{ dataset.pk }},
   url: '{% url 'datasets:update_description' dataset.pk %}',
   title: 'Edit dataset description',
    name: 'dataset-editable-description'
  });

  $('#dataset-species').editable({
   type: 'text',
   pk: {{ dataset.pk }},
   url: '{% url 'datasets:update_species' dataset.pk %}',
   title: 'Edit dataset species',
    name: 'dataset-editable-species'

  });
</script>

sepal/datasets/templates/datasets/datatable_init.html
{% load url from future %}
{% load staticfiles %}

{# DataTables #}
<script type="text/javascript" src='{{ STATIC_URL }}datatables/media/js/jquery.dataTables.min.js'></script>

{# TableTools #}
<script type="text/javascript" src='{{ STATIC_URL }}datatables/extras/TableTools/media/js/TableTools.min.js'></script>

<!-- FixedColumns -->
<script type="text/javascript" src='{{ STATIC_URL }}datatables/extras/FixedColumns/media/js/FixedColumns.min.js.gz'></script>

{# Scroller #}
<script type="text/javascript" src='{{ STATIC_URL }}datatables/extras/Scroller/media/js/dataTables.scroller.min.js'></script>

{# DataTables.net Bootstrap integration #}
<script type="text/javascript" src="{{ STATIC_URL }}datatables/media/js/dataTables.bootstrap.js"></script>

<script>
(function() {

/* GLOBAL CONSTANTS */
window.oTable;
window.oTT;
window.oFC;

var INITIAL_DISPLAY_LENGTH = 10;
// index of the date created column
var DATE_COLUMN = {{feature_names|length }} + {{label_names|length }} + 3;
var FILE_COLUMN = DATE_COLUMN - 1;
var LAST_COLUMN = DATE_COLUMN + 1;
var PLAY_BUTTON_COLUMN = 1
var FEATURE_COLUMNS = range(3, {{feature_names|length}});

function initializeTable() {
  // Initialize dataset as a DataTable
  oTable = $('#dataset-table').dataTable({
    "sDom": 'T<"clear">lfrtipS',
    "aaSorting": [
    [1, 'asc']
    ],
    "sScrollY": "287px",
    // affects the height of the table
    "sScrollX": "100%",
    "bScrollCollapse": true,
    // collapse table when filtering
    "bPaginate": false,
    "bDeferRender": false,
    "bStateSave": true,
    "oLanguage": {
      "sLengthMenu": " _MENU_ instances per page"
    },
    "iDisplayLength": INITIAL_DISPLAY_LENGTH,
    "bFilter": true,
    // Enable/disable search
    "fnDrawCallback": function(oSettings) { /* Need to redo the counters if filtered or sorted */
      if(oSettings.bSorted || oSettings.bFiltered) {
        for(var i = 0, iLen = oSettings.aiDisplay.length; i < iLen; i++) {
          var nTr = oSettings.aoData[oSettings.aiDisplay[i]].nTr;

          // Update the index column without redrawing the table
          this.fnUpdate(i + 1, nTr, 0, false, false);
        }
      }
    },
    "aoColumnDefs": [
    // Specifiy columns that aren't sortable
    {
      "bSortable": false,
      "sClass": "index",
      "aTargets": [0]
    }, {
      "bSortable": false,
      "aTargets": [PLAY_BUTTON_COLUMN, LAST_COLUMN]
    },
    // Make the date column wider so that it doesn't create 2 rows
    // {
    //   "sWidth": '30%',
    //   "aTargets": [FILE_COLUMN]
    // }, {
    //   "sWidth": '40%',
    //   "aTargets": [DATE_COLUMN]
    // }, 
    ],
    "oTableTools": {
      "sSwfPath": "{{ STATIC_URL }}datatables/extras/TableTools/media/swf/copy_csv_xls.swf",
      "sRowSelect": "multi",
      /* Datatable TableTools Buttons */
      "aButtons": [
      // Select All
      {
        "sExtends": "select_all",
        "sButtonClass": "btn",
        "sButtonText": '<i class="icon-check"></i> Select all'
      },
      // Select None
      {
        "sExtends": "select_none",
        "sButtonClass": "btn",
        "sButtonText": '<i class="icon-check-empty"></i> Deselect all'
      },

      // Change value
      {
        "sExtends": "text",
        "sButtonClass": "btn btn-green",
        "sButtonText": '<i class="icon-beaker"></i> Change value',
        "fnClick": function(nButton, oConfig, oFlash) {
          var ret = prompt("Enter the new value  : ", "");
          if(ret) {
            updateSelectedLabels(ret);
          }
        }
      },

      // Export csv
      {
        "sExtends": "csv",
        "sButtonClass": "btn btn-lightblue",
        "sButtonText": '<i class="icon-file"></i> Export'
      },

      // Delete selected
      {
        "sExtends": "text",
        "sButtonText": '<i class="icon-trash"></i>',
        "sButtonClass": "btn btn-red",
        "fnClick": function(nButton, oConfig, oFlash) {
          var answer = confirm("Delete selected instances?\nWARNING: This operation is irreversible.")
          if(answer) {
            deleteSelected();
          }
        }
      }]
    }
  });
}

/* Initialize the table */
$(function() {
  initializeTable();
  oTT = TableTools.fnGetInstance('dataset-table');
  // Fix left columns
  oFC = new FixedColumns(oTable, {
    "iLeftColumns": 2,
    "iLeftWidth": 85,
  });
});


/* Only include these functions if there is data,
otherwise, the url tags will cause an error. */
{% if not is_empty and label_names %}
/* 
function: deleteSelected()
Deletes the selected instances. 
Deletions persist to the db. */
function deleteSelected() {

  // var oTT = TableTools.fnGetInstance( 'dataset-table' );
  var selected = oTT.fnGetSelected(oTable);
  // Remove selected from table
  $.ajax({
    url: "{% url 'datasets:delete_instances' dataset.pk %}",
    type: "POST",
    data: {
      "selected": getSelectedIds(selected)
    },
    dataType: 'json',
    success: function(data) {
      oTT.fnSelectNone();
      // On success, dynamically delete selected rows from table
      $.each(selected, function(index, value) {
        oTable.fnDeleteRow(selected[index]);
      });
      // Update plot
      Viz.reloadData();
    },
    crossDomain: false,
    cache: false,
  });
}

/* 
function: updateSelectedLabels
Update the labels of the selected instances.
Changes persist to the db. */
function updateSelectedLabels(new_label) {
  var selected = oTT.fnGetSelected(oTable);
  // Remove selected from table
  $.ajax({
    url: "{% url 'datasets:update_instances_labels' dataset.pk label_name_id %}",
    type: "POST",
    data: {
      "new_label": new_label,
      "selected": getSelectedIds(selected)
    },
    dataType: 'json',
    success: function(data) {
      oTT.fnSelectNone();
      // Change each of the label texts to the new label
      $.each(selected, function(index, value) {
        $(value).find('td .instance-label')
          .text(new_label)
            .end()
          .removeClass('active')
          .addClass('success');
      });
      // Update plot
      Viz.reloadData();
    },
    crossDomain: false,
    cache: false,
  });
}   
{% endif %}

function getSelectedIds(selected) { 
  /* Returns an array of ids for the selected instances. */
  return $.map(selected, function(element) {
    return $(element).data('id');
  });
}

})();
</script>

sepal/datasets/templates/datasets/index.html
{% extends "base.html" %}
{% load url from future %}
{% block content_class %}container{% endblock content_class %}
{% block content %}
{# <div class="container"> #}
  <h1 class="page-title center">Datasets</h1>
  <div class="btn-toolbar">

    {% if user.is_authenticated %}
    <a href="{% url 'datasets:create' %}" data-toggle="modal" class="btn btn-blue">
      <i class="icon-plus"></i>
      Create Dataset
    </a>
    {% else %}
    <p>You need an account to create a dataset. Go to the home page to request an account.</p>
        <a href="{% url 'datasets:create' %}" data-toggle="modal" class="btn btn-blue">
      Home
    </a>
    {% endif %}
    <div class="btn-group">
    </div>
  </div>
  <div class="well">
    {% if all_datasets %}
    <table class="table">
      <thead>
        <tr>
          <th>Dataset</th>
          <th>Description</th>
          <th>Species</th>
          <th>Date Created</th>
        </tr>
      </thead>
      {% for dataset in all_datasets %}
      <tr>
        <td><a href="{{ dataset.pk }}">
          <i class="icon-table"></i>
          {{ dataset.name }}</a>
        </td>
        <td>{{ dataset.description }}</td>
        <td class="species">{{ dataset.species }}</td>
        <td>{{ dataset.created_at }}</td>
        <td>
          <a href="{% url 'datasets:edit' dataset.pk %}" class="edit"><i class="icon-pencil"></i></a>
{#           <a href="{% url 'datasets:delete_dataset' dataset.pk %}" role="button"><i class="icon-remove"></i></a> #}
          <a id="delete_dataset_{{ dataset.pk }}" href="#delete_dataset_{{ dataset.pk }}_confirm" data-id="{{ dataset.pk }}"><i class="icon-remove"></i></a>
        </td>
      {% include "datasets/confirm_delete_dataset.html" %}
      </tr>
      {% endfor %}
    </table>
    {% else %}
    <h3 class="center"><em>No datasets available.</em></h3>
    {% endif %}
  </div>{# end div.well #}
{# </div> #}
{% endblock content %}

sepal/datasets/templates/datasets/show_dataset.html
{% load url from future %}
<div class="m-widget span12">
  <div id="dataset-heading" class="m-widget-header"><h3>Table</h3></div>
  <div id="m-widget-body" class="block-body">
    <table cellpadding="0" cellspacing="0" border="0" id="dataset-table" class="table table-striped">
      {# Header #}
      <thead>
        <tr>
          {# Only show header if there are instances #}
          {% if not is_empty %}
          <th class="fixed-col" rowspan="1">#</th>
          <th class="fixed-col" rowspan="1"></th>
          
          {% for label_name in label_names %}
          <th rowspan="1"><i class="icon-beaker"></i><a href="#" class="label_name" id="label_name{{ label_name.pk }}"> {{ label_name|capfirst }}</a></th>
          <script>
          $('#label_name{{ label_name.pk }}').editable({
           type: 'text',
           showbuttons: false,
           pk: {{ label_name.pk }},
           url: '{% url 'datasets:update_label_name' dataset.pk label_name.pk  %}',
           value: '',
           title: 'Edit label name'
         });
          </script>
          {% endfor %}
          {% for feature in feature_objects %}
          <th>{{ feature.display_name }}</th>
          {% endfor %}
          <th>File</th>
          <th>Date added</th>
          <th></th>
          {% endif %}
        </tr>
      </thead>

      {# Data #}
      <tbody>
        {% for inst in data %}
        <tr data-id="{{ inst.pk }}" data-row="{{ forloop.counter }}">
          {# Index #}
          {# This will be dynamically drawn at DataTable initialization #}
          <td></td>

          {# Play button #}
          <td class="fixed-col">
            {% if inst.audio_url %}
            <a href="{{ inst.audio_url }}" class="sm2_button">{{ inst.pk }}</a>
            {% endif %}
          </td>


          {# Variable value #}
          {% if inst.labels %}
          {% for label_name, label_value in inst.labels.items %}
          <td><a href="#" class="instance-label" data-id="{{ inst.pk }}" data-value="{{ label_value }}">{{ label_value }}</a></td>
          {# Initiate editable label value #}
          <script>
          $(".instance-label[data-id={{ inst.pk }}]").editable({
           type: 'text',
           showbuttons: false,
           pk: {{ inst.pk }},
           url: "{% url 'datasets:update_instance_label' dataset.pk inst.pk label_name.pk  %}",
           value: '',
           title: 'Edit instance label',
           success: function(data, new_label){
              Viz.reloadData();
          }
          });
          </script>
          {% endfor %}
          {% else %}
          <td>No label</td>
          {% endif %}
          
          {# Values #}
          {% for value in inst.values %}
          <td>{{ value|floatformat:-6 }}</td>
          {% endfor %}
          
          {# File #}
          <td>
            {% if inst.audio_url %}
            <a href="{{ inst.audio_url }}">{{ inst.audio_filename }}</a>
            {% endif %}
          </td>

          {# Created at #}
          <td>{{ inst.created_at|date:"m/d/Y f a" }}</td>

          {# Delete #}
          <td><a href="{% url 'datasets:single_instance_delete' dataset.pk inst.pk %}"><i class="icon-remove"></i></a></td>

        </tr>
        {% endfor %}
      </tbody>
    </table>
  </div>
</div>