sepal/base/urls.py
"""urlconf for the base application"""

from django.conf.urls.defaults import url, patterns

urlpatterns = patterns('sepal.base.views',
    url(r'^$', 'home', name='home'),
    url(r'^documentation/$', 'documentation', name='documentation')
)

sepal/datasets/urls.py
'''urlconf for sepal.datasets'''

from django.conf.urls.defaults import url, patterns
from sepal.datasets.views import *

urlpatterns = patterns('',
    # ex: /datasets/
    url(r'^$', DatasetList.as_view(), name='index'),

    # ex: /datasets/3/
    url(r'^(?P<pk>\d+)/$', DatasetDetail.as_view(),
        name='detail'),

    # ex: /datasets/new/
    url(r'^create/$', DatasetCreate.as_view(), name='create'),

    # ex: /datasets/3/edit/
    url(r'^(?P<pk>\d+)/edit/$', DatasetEdit.as_view(),
        name='edit'),

    # ex: /datasets/3/upload/
    url(r'^(?P<pk>\d+)/upload/$', multiple_uploader,
        name='upload'),

    # ex: /datasets/3/delete/
    url(r'^(?P<pk>\d+)/delete/$', delete_dataset,
        name='delete_dataset'),

    # ex: /datasets/3/delete_instances/
    url(r'^(?P<pk>\d+)/delete_instances/$', delete_instances,
        name='delete_instances'),
    
    # ex: /datasets/3/instances/452/delete/
    url(r'^(?P<dataset_id>\d+)/instances/(?P<pk>\d+)/delete/$',
        SingleInstanceDelete.as_view(),
        name='single_instance_delete'),

    # ex: /datasets/3/update_instances_labels/
    url(r'^(?P<dataset_id>\d+)/update_instances_labels/(?P<label_name_id>\d+)$',
        update_instances_labels,
        name='update_instances_labels'),

    # ex: /datasets/3/load_data
    url(r'^(?P<pk>\d+)/load_data/$', load_data,
        name='load_data'),
)

# URLconfs for X-editable updating
urlpatterns += patterns('',
    # ex: /datasets/3/update_name
    # X-editable dataset name
    url(r'^(?P<dataset_id>\d+)/update_name/$', update_name,
        name='update_name'),

    # ex: /datasets/3/update_description
    # X-editable dataset name
    url(r'^(?P<dataset_id>\d+)/update_description/$', update_description,
        name='update_description'),

    # ex: /datasets/3/update_description
    # X-editable dataset name
    url(r'^(?P<dataset_id>\d+)/update_species/$', update_species,
        name='update_species'),

    # ex: /datasets/instances/452/update_label/4
    # X-editable instance label
    url(r'^(?P<dataset_id>\d+)/instances/(?P<instance_id>\d+)/update_label/(?P<label_name_id>\d+)$',
        update_instance_label,
        name='update_instance_label'),

    # ex: /datasets/3/update_label/5
    # X-editable label name
    url(r'^(?P<dataset_id>\d+)/update_label/(?P<label_name_id>\d+)$',
        update_label_name,
        name='update_label_name'),
)

sepal/urls.py
""" Default urlconf for sepal """

from django.conf import settings
from django.conf.urls.defaults import include, patterns
from django.contrib import admin
admin.autodiscover()

def bad(request):
    """ Simulates a server error """
    1 / 0

urlpatterns = patterns('',
    (r'', include('sepal.base.urls')),
    (r'^celerytest/', include('sepal.celerytest.urls', namespace='celery')),
    (r'^datasets/', include('sepal.datasets.urls', namespace='datasets')),
    (r'^user/', include('sepal.user.urls', namespace='user')),
    (r'^signup/', include('sepal.signup.urls', namespace='signup')),
    (r'^admin/doc/', include('django.contrib.admindocs.urls')),
    (r'^admin/', include(admin.site.urls)),
    #url(r'^', include('debug_toolbar_user_panel.urls')),
    (r'^bad/$', bad),
)

## In DEBUG mode, serve media files through Django.
if settings.DEBUG:
    # Remove leading and trailing slashes so the regex matches.
    media_url = settings.MEDIA_URL.lstrip('/').rstrip('/')
    urlpatterns += patterns('',
        (r'^%s/(?P<path>.*)$' % media_url, 'django.views.static.serve',
         {'document_root': settings.MEDIA_ROOT}),
    )

sepal/user/urls.py
# The views used below are normally mapped in django.contrib.admin.urls.py
# This URLs file is used to provide a reliable view deployment for test purposes.
# It is also provided as a convenience to those who want to deploy these URLs
# elsewhere.

from django.conf.urls import patterns, url

urlpatterns = patterns('',
    url(r'^login/$', 'django.contrib.auth.views.login', {'template_name': 'user/login_form.html'}, name='login'),
    url(r'^logout/$', 'django.contrib.auth.views.logout', {'template_name': 'base/home.html'}, name='logout'),
    url(r'^password_change/$', 'django.contrib.auth.views.password_change', {'template_name': 'user/password_change_form.html', 'post_change_redirect': '/user/password_change/done/'}, name='password_change'),
    url(r'^password_change/done/$', 'django.contrib.auth.views.password_change_done', {'template_name': 'user/password_change_done.html'}, name='password_change_done'),
    url(r'^password_reset/$', 'django.contrib.auth.views.password_reset', {'template_name': 'user/password_reset_form.html', 'post_reset_redirect': 'user/password_reset/done/'}, name='password_reset'),
    url(r'^password_reset/done/$', 'django.contrib.auth.views.password_reset_done', {'template_name': 'user/password_reset_done.html'}, name='password_reset_done'),
    url(r'^reset/(?P<uidb36>[0-9A-Za-z]{1,13})-(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$',
        'django.contrib.auth.views.password_reset_confirm', { 'post_reset_redirect': '/user/reset/done/' },
        name='password_reset_confirm'),
    url(r'^reset/done/$', 'django.contrib.auth.views.password_reset_complete', {'template_name': 'user/password_reset_complete.html'}, name='password_reset_complete'),
)

sepal/base/models.py
""" Basic models, such as user profile """

sepal/base/views.py
""" Views for the base application """

from django.shortcuts import render_to_response
from django.template import RequestContext


def home(request):
    """ Default view for the root """
    return render_to_response('base/home.html',
        context_instance=RequestContext(request))

def documentation(request):
    """View for the documentation"""
    return render_to_response('base/documentation.html',
        context_instance=RequestContext(request))

sepal/base/templates/base.html
{% load staticfiles %}
<!DOCTYPE html>
<!-- paulirish.com/2008/conditional-stylesheets-vs-css-hacks-answer-neither/ -->
<!--[if lt IE 7]> <html class="no-js lt-ie9 lt-ie8 lt-ie7" lang="en"> <![endif]-->
<!--[if IE 7]>    <html class="no-js lt-ie9 lt-ie8" lang="en"> <![endif]-->
<!--[if IE 8]>    <html class="no-js lt-ie9" lang="en"> <![endif]-->
<!-- Consider adding a manifest.appcache: h5bp.com/d/Offline -->
<!--[if gt IE 8]><!--> <html class="no-js" lang="en"> <!--<![endif]-->
<head>
  <meta charset="utf-8">

  <!-- Use the .htaccess and remove these lines to avoid edge case issues.
  More info: h5bp.com/i/378 -->
  <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">

  <title>{% block page_title %}{{ _("sepal | Audio feature extraction and analysis made simple") }}{% endblock %}</title>
  <meta name="description" content="{% block meta_description %}{% endblock %}">
  <meta name="author" content="{% block meta_author %}{% endblock %}">

  <!-- Mobile viewport optimized: h5bp.com/viewport -->
  <meta name="viewport" content="width=device-width">

  <!-- Place favicon.ico and apple-touch-icon.png in the root directory: mathiasbynens.be/notes/touch-icons -->

  {# Base app styling #}
  <link rel="stylesheet" href="{{ STATIC_URL }}css/style.css">

  {# Fonts #}
  <link href='http://fonts.googleapis.com/css?family=Droid+Serif|Droid+Sans' rel='stylesheet' type='text/css'>

  {# Grab Google CDN's jQuery, with a protocol relative URL; fall back to local if offline #}
  <script src="//ajax.googleapis.com/ajax/libs/jquery/1.8.3/jquery.min.js"></script>
  <script>window.jQuery || document.write('<script src="{{ STATIC_URL }}js/libs/jquery-1.8.3.min.js"><\/script>')</script>

  {# Jquery cookie plugin #}
  <script src=" {{ STATIC_URL }}jquery-cookie-master/jquery.cookie.js"></script>

  {# Include X-editable #}
  <script src="{{ STATIC_URL }}bootstrap-editable/js/bootstrap-editable-inline.min.js"></script>

  {# App-specific scripts #}
  <script src="{{ STATIC_URL }}js/script.js"></script>

  {% block static %}{% endblock %}

  <!-- Prompt IE 6 users to install Chrome Frame. Remove this if you support IE 6.
  chromium.org/developers/how-tos/chrome-frame-getting-started -->
  <!--[if lt IE 7]><p class=chromeframe>Your browser is <em>ancient!</em> <a href="http://browsehappy.com/">Upgrade to a different browser</a> or <a href="http://www.google.com/chromeframe/?redirect=true">install Google Chrome Frame</a> to experience this site.</p><![endif]-->
</head>

<body class="{% block body_class %}{% endblock %}">

  {% include "nav.html" %}
  
  {% block header %}{% endblock %}


  
  <div class="{% block content_class %}container-fluid{% endblock content_class %}">

    {% comment %}
    <div id="main">
      <div class="alert alert-info">
        <strong>IMPORTANT:</strong> Sepal is currently in its early stages and is for evaluation only. Make sure your audio is backed up in a safe place.
      </div>
      
    {% endcomment %}

      {% if messages %}
          {% for message in messages %}
          <div class="alert alert-{{message.tags}} fade in">
            <a class="close" title="Close" href="#" data-dismiss="alert">&times;</a>
            <strong>{{message.tags|title}}:</strong> {{message}}
          </div>
          {% endfor %}
      {% endif %}
      {% block content %}{% endblock %}
    </div>

  </div>

  {% include "footer.html" %}


  <!-- Other JavaScript at the bottom for fast page loading -->
  {# D3 #}
  <script src="{{ STATIC_URL }}d3/d3.v3.min.js"></script>
  <!-- scripts concatenated and minified via build script -->
  <script src="{{ STATIC_URL }}bootstrap/js/bootstrap.min.js"></script>
  <script src="{{ STATIC_URL }}js/plugins.js"></script>

  {# Google analytics snippet #}
  <script type="text/javascript">
  var _gaq = _gaq || [];
  _gaq.push(['_setAccount', 'UA-38106995-2']);
  _gaq.push(['_trackPageview']);

  (function() {
    var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
    ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
    var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
  })();
  </script>
  {% block scripts %}{% endblock scripts %}

  {# Wishbox for feedback #}
  {% if user.is_authenticated %}
    {% include "wishbox.html" %}
  {% endif %}
  <!-- end scripts -->
</body>
</html>

sepal/base/templates/footer.html
<footer>
  <small>
  <ul class="company">
    <li>© SEPAL Bioacoustics, LLC 2013</li>
    <li><a href="mailto:sepalproject@gmail.com">Contact</a></li>
  </ul>
    <p class='help'>
    For best results, use the latest version of 
    <a href="https://www.google.com/intl/en/chrome/">Google Chrome</a> or 
    <a href="http://www.apple.com/safari/">Safari</a>.
    </p>
  </small>
</footer>

sepal/base/templates/nav.html
{% load staticfiles %}
{% load url from future %}
<div class="navbar navbar-inverse">
  <div class="navbar-inner">
      <a href="{% url 'home' %}" class="brand"><i class="icon-leaf"></i> sepal</a>
        <ul class="nav">
          <li><a href="{% url 'home' %}">Home</a></li>
          {% if user.is_authenticated %} 
          <li><a href="{% url 'datasets:index' %}">Datasets</a></li>
          {% endif %}
        </ul>
        {% if user.is_authenticated %}

        <ul class="nav pull-right">
          <li><a>Logged in as {{ user.username }}</a></li>
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle='dropdown'>
              Manage account
              <b class='caret'></b>
            </a>
            <ul class="dropdown-menu">
              <li><a href="{% url 'user:password_change' %}">Change password</a></li>
              <li><a href="{% url 'user:password_reset' %}">Reset password</a></li>
            </ul>
          </li><!-- end dropdown -->
          <li>
          <form id='logoutForm' class="navbar-form pull-right" action="{% url 'user:logout' %}" method="get">
          <button type="submit" class="btn btn-small">Log Out</button>
        </form>
          </li>
        </ul>
        {% else %}
        <form id="loginForm" class="navbar-form pull-right" action="{% url 'user:login' %}" method="post">
          {% csrf_token %}
          <input class="span2" type="text" name="username" placeholder="Email" />
          <input class="span2" type="password" name="password" placeholder="Password" />
          <button type="submit" class="btn btn-small">Log In</button>
        </form>
        {% if form.errors %}
          <ul class="nav pull-right error">
            <li><a>Your username and password didn't match!</a></li>
          </ul>
        {% endif %}
        {% endif %}
  </div>
</div>

sepal/base/templates/wishbox.html
<script src="http://www.jotform.com/min/?g=feedback2" type="text/javascript"></script>
<script type="text/javascript">
    new JotformFeedback({
        formId      : "30590879306158",
        buttonText  : "Feedback",
        windowTitle : "Mark up the screenshot to describe a problem or suggestion",
        base        : "http://jotform.us/",
        background  : "#faa732",
        fontColor   : "#FFFFFF",
        buttonSide  : "top",
        buttonAlign : "center",
        type        : false,
        width       : 280,
        height      : 420,
        instant     : true
    });
</script>